Document: mlde.l.cppmicroservices
Title: Debian mlde.l.cppmicroservices Manual
Author: <insert document author here>
Abstract: This manual describes what mlde.l.cppmicroservices is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mlde.l.cppmicroservices/mlde.l.cppmicroservices.sgml.gz

Format: postscript
Files: /usr/share/doc/mlde.l.cppmicroservices/mlde.l.cppmicroservices.ps.gz

Format: text
Files: /usr/share/doc/mlde.l.cppmicroservices/mlde.l.cppmicroservices.text.gz

Format: HTML
Index: /usr/share/doc/mlde.l.cppmicroservices/html/index.html
Files: /usr/share/doc/mlde.l.cppmicroservices/html/*.html
